"""initial tables

Revision ID: e3b3776a14b3
Revises: f5c9b2d03e41
Create Date: 2026-08-18 12:46:31.663647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b3776a14b3'
down_revision: Union[str, Sequence[str], None] = 'f5c9b2d03e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('short_info', sa.String(), nullable=True),
    sa.Column('webinar_ids', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experts_id'), 'experts', ['id'], unique=False)
    op.create_table('rubrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rubrics_id'), 'rubrics', ['id'], unique=False)
    op.create_table('site_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_links_id'), 'social_links', ['id'], unique=False)
    op.create_table('webinars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('talk_points', sa.Text(), nullable=True),
    sa.Column('video_links', sa.Text(), nullable=True),
    sa.Column('expert_id', sa.Integer(), nullable=True),
    sa.Column('question_url', sa.String(), nullable=True),
    sa.Column('stream_url', sa.String(), nullable=True),
    sa.Column('preview', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webinars_expert_id'), 'webinars', ['expert_id'], unique=False)
    op.create_index(op.f('ix_webinars_id'), 'webinars', ['id'], unique=False)
    op.create_table('webinar_rubrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webinar_id', sa.Integer(), nullable=False),
    sa.Column('rubric_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], ),
    sa.ForeignKeyConstraint(['webinar_id'], ['webinars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('webinar_id', 'rubric_id', name='uq_webinar_rubric')
    )
    op.create_index(op.f('ix_webinar_rubrics_id'), 'webinar_rubrics', ['id'], unique=False)
    op.create_index(op.f('ix_webinar_rubrics_rubric_id'), 'webinar_rubrics', ['rubric_id'], unique=False)
    op.create_index(op.f('ix_webinar_rubrics_webinar_id'), 'webinar_rubrics', ['webinar_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webinar_rubrics_webinar_id'), table_name='webinar_rubrics')
    op.drop_index(op.f('ix_webinar_rubrics_rubric_id'), table_name='webinar_rubrics')
    op.drop_index(op.f('ix_webinar_rubrics_id'), table_name='webinar_rubrics')
    op.drop_table('webinar_rubrics')
    op.drop_index(op.f('ix_webinars_id'), table_name='webinars')
    op.drop_index(op.f('ix_webinars_expert_id'), table_name='webinars')
    op.drop_table('webinars')
    op.drop_index(op.f('ix_social_links_id'), table_name='social_links')
    op.drop_table('social_links')
    op.drop_table('site_content')
    op.drop_index(op.f('ix_rubrics_id'), table_name='rubrics')
    op.drop_table('rubrics')
    op.drop_index(op.f('ix_experts_id'), table_name='experts')
    op.drop_table('experts')
    # ### end Alembic commands ###
